<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>log</string>
	</array>
	<key>name</key>
	<string>Android Logs</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>header.border</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>header</string>
			<key>match</key>
			<string>^(\*+).*$</string>
			<key>name</key>
			<string>header.content</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>entry date</string>
			<key>match</key>
			<string>^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}</string>
			<key>name</key>
			<string>log.entry.date</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>log.entry.level.info</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>log.entry.tag.info</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>info tag</string>
			<key>match</key>
			<string>(I)(/[^:]+):</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>log.entry.level.warn</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>log.entry.tag.warn</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>warn tag</string>
			<key>match</key>
			<string>(W)(/[^:]+):</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>log.entry.level.error</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>log.entry.tag.error</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>error tag</string>
			<key>match</key>
			<string>(E)(/[^:]+):</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>log.entry.level</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>log.entry.tag</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>other tags</string>
			<key>match</key>
			<string>(\w)(/[^:]+):</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>url</string>
			<key>match</key>
			<string>http(?:s?)://\S+</string>
			<key>name</key>
			<string>log.entry.content.url</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>sql</string>
			<key>match</key>
			<string>(?:SELECT|UPDATE|DELETE) .*</string>
			<key>name</key>
			<string>log.entry.content.sql</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>log.stacktrace.exception</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>stacktrace</string>
			<key>match</key>
			<string>\w*?(?:Exception|Error) (?:.*? )((?:\w+\.)*\w+)$</string>
			<key>name</key>
			<string>log.stacktrace</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>log.stacktrace.class</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>log.stacktrace.file</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>log.stacktrace.line</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>stacktrace2</string>
			<key>match</key>
			<string>\s+at ((?:\w+\.)*\w+)\((\w+\.\w+):(\d+)\)</string>
			<key>name</key>
			<string>log.stacktrace</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.android_logs</string>
	<key>uuid</key>
	<string>50d81c69-4898-4545-998b-0ab147e783f2</string>
</dict>
</plist>
